{{- /* Define a recursive function to convert structured data to a plain string YAML */ -}}
{{- define "structuredToPlainString" -}}
  {{- printf "%v" (toYaml . | trimSuffix "\n") -}}
{{- end -}}

{{- range $objKey, $objValue := .Values.extraObjects }}
---
{{- if typeIs "string" $objValue }}
{{ tpl $objValue $ }}
{{- else if hasKey $objValue "stringData" }}
apiVersion: v1
kind: Secret
metadata:
{{ toYaml $objValue.metadata | indent 2 }}
stringData:
{{- range $key, $value := $objValue.stringData }}
  {{ $key }}: {{ include "structuredToPlainString" $value }}
{{- end }}
{{- else }}
{{ toYaml $objValue }}
{{- end }}
{{- end }}
