{{- /* Define a recursive function to convert structured data to a plain string YAML */ -}}
{{- define "structuredToPlainString" -}}
  {{- printf "%v" (toYaml . | trimSuffix "\n") -}}
{{- end -}}

{{- /* Define a function to check if a string has multiple lines */ -}}
{{- define "isMultiline" -}}
  {{- if gt (sub (len .) (len (replace . "\n" ""))) 0 -}}
  true
  {{- else -}}
  false
  {{- end -}}
{{- end -}}

{{- range $objKey, $objValue := .Values.extraObjects }}
---
{{- if and (eq $objValue.kind "Secret") (hasKey $objValue "stringData") }}
apiVersion: v1
kind: Secret
{{- range $key, $value := $objValue }}
{{- if eq $key "stringData" }}
stringData:
{{- range $sdKey, $sdValue := $value }}
  {{ $sdKey }}:
  {{- if eq (include "isMultiline" (include "structuredToPlainString" $sdValue)) "true" }}
    |{{ include "structuredToPlainString" $sdValue | nindent 6 }}
  {{- else }}
    {{ include "structuredToPlainString" $sdValue }}
  {{- end }}
{{- end }}
{{- else }}
{{ $key }}:
{{ toYaml $value | indent 2 }}
{{- end }}
{{- end }}
{{- else }}
{{ toYaml $objValue | nindent 0 }}
{{- end }}
{{- end }}
