{{- /* Define a recursive function to convert structured data to a plain string YAML */ -}}
{{- define "structuredToPlainString" -}}
  {{- printf "%v" (toYaml . | trimSuffix "\n") -}}
{{- end -}}

{{- range .Values.extraObjects }}
---
{{- if typeIs "string" . -}}
{{ tpl . $ }}
{{- else }}
{{- if .stringData -}}
apiVersion: v1
kind: Secret
metadata:
{{ toYaml .metadata | indent 2 }}
stringData:
{{- range $key, $value := .stringData }}
  {{ $key }}: {{ include "structuredToPlainString" $value }}
{{- end }}
{{- else -}}
{{- range $key, $value := . }}
{{ $key }}: 
  {{- if typeIs "map[string]interface {}" $value -}}
{{ toYaml $value | indent 2 }}
  {{- else -}}
{{ $value | quote }}
  {{- end -}}
{{- end }}
{{- end -}}
{{- end }}
{{- end }}
