{{- /* Define a recursive function to convert structured data to a plain string YAML */ -}}
{{- define "structuredToPlainString" -}}
  {{- printf "%v" (toYaml . | trimSuffix "\n") -}}
{{- end -}}

{{- range $objKey, $objValue := .Values.extraObjects }}
---
{{- if and (eq $objValue.kind "Secret") (hasKey $objValue "stringData") }}
apiVersion: v1
kind: Secret
{{- range $key, $value := $objValue }}
{{- if eq $key "stringData" }}
stringData:
{{- range $sdKey, $sdValue := $value }}
  {{ $sdKey }}: {{ include "structuredToPlainString" $sdValue }}
{{- end }}
{{- else }}
{{ $key }}:
{{ toYaml $value | indent 2 }}
{{- end }}
{{- end }}
{{- else }}
{{ toYaml $objValue }}
{{- end }}
{{- end }}
